### ISSUE TITLE
Transfer to VueUse

### ISSUE THREAD

**Issue by Rolanddoda** [antfu/vue-reuse-template#2]
### Clear and concise description of the problem

This looks really awesome! 
However, I think it would make more sense to include it in an already existing dependency.

### Suggested solution

Personally I think that would be a great addition to Vue core and would enable so many refactors but I think it's better to have it in VueUse. Almost every Vue3 project uses or will eventually use VueUse so having this in VueUse will save us one extra dependency

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Maybe, let's see :)

**Comment by TonyYanOnFire** [comment]
In that case, will this feature be supported in Vue2.7? If so, it would be even better👏

**Comment by Jurool** [comment]
> In that case, will this feature be supported in Vue2.7? If so, it would be even better👏

expect@antfu

**Comment by avinean** [comment]
@antfu transfer to vue

**Comment by zzx58-027** [comment]
expect ➕1️⃣

**Comment by enkot** [comment]
@antfu transfer to Svelte

**Comment by AndrewBogdanovTSS** [comment]
@antfu will have to invent a clone machine to support all your requests, guys 😂
