### ISSUE TITLE
ReuseTemplate error

### ISSUE THREAD

**Issue by hminghe** [antfu/vue-reuse-template#4]
### Describe the bug

`ReuseTemplate` is slot

```html
<template>
  <Comp >
    <!-- ERROR -->
    <!-- getCurrentInstance().parent === <Comp /> -->
    <ReuseTemplate />
  </Comp>
 
  <!-- getCurrentInstance().parent === CurrentComp   -->
  <ReuseTemplate />
</template>
```

### Reproduction

https://play.vuejs.org/#eNqVUctqwzAQ/JWNL3Yglum12IGSS3sthV4MwTgbY9ALaR0oIf9eSVbcuglue9PsY3ZmdE6etGanAZPHpLSt6TWBRRr0tpa90MoQnMHgES5wNEpA6kbTqbVTQsc6KzzwTF/tVxwsvqHQvCGc5mbVuFDLshivu7sOUGw7BFCGM+HpwCrPoUPaDcagpBdpqZEtZmumG1+AqqriRrGFPL+uzbUUI3HQ7J8B/YnZxfWN+A5tWUzik01yDeV/8dayVe48CNtB5ftZ+oycK3hXhh9W6Xo5r0N/Co+aSssVRbcArRMz+p4mfsi9+ZtfdG/uBHbjZXSjODKuumwhYUYfGtl+LxuByxa9k4e5+Msnq5D1uA==

### System Info

```Shell
G
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hminghe** [comment]
我暂时想到的只有， 删除 `DefineTemplate` 和 `ReuseTemplate` 两个组件， 只用 `createReusableTemplate` 定义，createReusableTemplate 时，内部自己维护 `TemplateRegistry`

**Comment by antfu** [comment]
Nice catch. I thought `.parent` would be the component creating it.

And yeah, I have to remove the default component to fix it for now. I will try to explore other solutions in the mean time
